/*
 * generated by Xtext
 */
package org.scribble.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.scribble.ui.internal.ScribbleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ScribbleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ScribbleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ScribbleActivator.getInstance().getInjector(ScribbleActivator.ORG_SCRIBBLE_SCRIBBLE);
	}
	
}
