/*
* generated by Xtext
*/
package org.scribble.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.scribble.services.ScribbleGrammarAccess;

public class ScribbleParser extends AbstractContentAssistParser {
	
	@Inject
	private ScribbleGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.scribble.ui.contentassist.antlr.internal.InternalScribbleParser createParser() {
		org.scribble.ui.contentassist.antlr.internal.InternalScribbleParser result = new org.scribble.ui.contentassist.antlr.internal.InternalScribbleParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGlobalInteractionAccess().getAlternatives(), "rule__GlobalInteraction__Alternatives");
					put(grammarAccess.getScribbleProgramAccess().getGroup(), "rule__ScribbleProgram__Group__0");
					put(grammarAccess.getIncludeDeclAccess().getGroup(), "rule__IncludeDecl__Group__0");
					put(grammarAccess.getInstGlobalProtocolDeclAccess().getGroup(), "rule__InstGlobalProtocolDecl__Group__0");
					put(grammarAccess.getInstGlobalProtocolDeclAccess().getGroup_6(), "rule__InstGlobalProtocolDecl__Group_6__0");
					put(grammarAccess.getTypeDeclAccess().getGroup(), "rule__TypeDecl__Group__0");
					put(grammarAccess.getTypeDeclAccess().getGroup_7(), "rule__TypeDecl__Group_7__0");
					put(grammarAccess.getGlobalProtocolDeclAccess().getGroup(), "rule__GlobalProtocolDecl__Group__0");
					put(grammarAccess.getGlobalProtocolDeclAccess().getGroup_3(), "rule__GlobalProtocolDecl__Group_3__0");
					put(grammarAccess.getGlobalProtocolDeclAccess().getGroup_3_3(), "rule__GlobalProtocolDecl__Group_3_3__0");
					put(grammarAccess.getGlobalProtocolDeclAccess().getGroup_5(), "rule__GlobalProtocolDecl__Group_5__0");
					put(grammarAccess.getGlobalProtocolDeclAccess().getGroup_5_2(), "rule__GlobalProtocolDecl__Group_5_2__0");
					put(grammarAccess.getGlobalInteractionBlockAccess().getGroup(), "rule__GlobalInteractionBlock__Group__0");
					put(grammarAccess.getSpawnAccess().getGroup(), "rule__Spawn__Group__0");
					put(grammarAccess.getSpawnAccess().getGroup_3(), "rule__Spawn__Group_3__0");
					put(grammarAccess.getSpawnAccess().getGroup_3_3(), "rule__Spawn__Group_3_3__0");
					put(grammarAccess.getSpawnAccess().getGroup_8(), "rule__Spawn__Group_8__0");
					put(grammarAccess.getDoAccess().getGroup(), "rule__Do__Group__0");
					put(grammarAccess.getDoAccess().getGroup_2(), "rule__Do__Group_2__0");
					put(grammarAccess.getDoAccess().getGroup_2_2(), "rule__Do__Group_2_2__0");
					put(grammarAccess.getDoAccess().getGroup_7(), "rule__Do__Group_7__0");
					put(grammarAccess.getInterruptibleAccess().getGroup(), "rule__Interruptible__Group__0");
					put(grammarAccess.getInterruptibleAccess().getGroup_6(), "rule__Interruptible__Group_6__0");
					put(grammarAccess.getContinueAccess().getGroup(), "rule__Continue__Group__0");
					put(grammarAccess.getRecursionAccess().getGroup(), "rule__Recursion__Group__0");
					put(grammarAccess.getParallelAccess().getGroup(), "rule__Parallel__Group__0");
					put(grammarAccess.getParallelAccess().getGroup_2(), "rule__Parallel__Group_2__0");
					put(grammarAccess.getChoiceAccess().getGroup(), "rule__Choice__Group__0");
					put(grammarAccess.getChoiceAccess().getGroup_4(), "rule__Choice__Group_4__0");
					put(grammarAccess.getMessageAccess().getGroup(), "rule__Message__Group__0");
					put(grammarAccess.getMessageSignatureAccess().getGroup(), "rule__MessageSignature__Group__0");
					put(grammarAccess.getMessageSignatureAccess().getGroup_2(), "rule__MessageSignature__Group_2__0");
					put(grammarAccess.getMessageSignatureAccess().getGroup_2_1(), "rule__MessageSignature__Group_2_1__0");
					put(grammarAccess.getPayloadTypeAccess().getGroup(), "rule__PayloadType__Group__0");
					put(grammarAccess.getScribbleProgramAccess().getIncludeDeclAssignment_0(), "rule__ScribbleProgram__IncludeDeclAssignment_0");
					put(grammarAccess.getScribbleProgramAccess().getTypeDeclAssignment_1(), "rule__ScribbleProgram__TypeDeclAssignment_1");
					put(grammarAccess.getScribbleProgramAccess().getGlobalProtocolDeclAssignment_2(), "rule__ScribbleProgram__GlobalProtocolDeclAssignment_2");
					put(grammarAccess.getScribbleProgramAccess().getInstGlobalProtocolDeclAssignment_3(), "rule__ScribbleProgram__InstGlobalProtocolDeclAssignment_3");
					put(grammarAccess.getIncludeDeclAccess().getImportURIAssignment_1(), "rule__IncludeDecl__ImportURIAssignment_1");
					put(grammarAccess.getInstGlobalProtocolDeclAccess().getProtocolNameAssignment_2(), "rule__InstGlobalProtocolDecl__ProtocolNameAssignment_2");
					put(grammarAccess.getInstGlobalProtocolDeclAccess().getRolesAssignment_5(), "rule__InstGlobalProtocolDecl__RolesAssignment_5");
					put(grammarAccess.getInstGlobalProtocolDeclAccess().getRolesAssignment_6_2(), "rule__InstGlobalProtocolDecl__RolesAssignment_6_2");
					put(grammarAccess.getInstGlobalProtocolDeclAccess().getInstantiatedProtocolAssignment_9(), "rule__InstGlobalProtocolDecl__InstantiatedProtocolAssignment_9");
					put(grammarAccess.getTypeDeclAccess().getTypeNameAssignment_1(), "rule__TypeDecl__TypeNameAssignment_1");
					put(grammarAccess.getTypeDeclAccess().getSchemaAssignment_4(), "rule__TypeDecl__SchemaAssignment_4");
					put(grammarAccess.getTypeDeclAccess().getFileAssignment_6(), "rule__TypeDecl__FileAssignment_6");
					put(grammarAccess.getTypeDeclAccess().getAliasAssignment_7_1(), "rule__TypeDecl__AliasAssignment_7_1");
					put(grammarAccess.getGlobalProtocolDeclAccess().getProtocolNameAssignment_2(), "rule__GlobalProtocolDecl__ProtocolNameAssignment_2");
					put(grammarAccess.getGlobalProtocolDeclAccess().getParametersAssignment_3_2(), "rule__GlobalProtocolDecl__ParametersAssignment_3_2");
					put(grammarAccess.getGlobalProtocolDeclAccess().getParametersAssignment_3_3_2(), "rule__GlobalProtocolDecl__ParametersAssignment_3_3_2");
					put(grammarAccess.getGlobalProtocolDeclAccess().getRolesAssignment_5_1(), "rule__GlobalProtocolDecl__RolesAssignment_5_1");
					put(grammarAccess.getGlobalProtocolDeclAccess().getRolesAssignment_5_2_2(), "rule__GlobalProtocolDecl__RolesAssignment_5_2_2");
					put(grammarAccess.getGlobalProtocolDeclAccess().getBodyAssignment_7(), "rule__GlobalProtocolDecl__BodyAssignment_7");
					put(grammarAccess.getGlobalInteractionBlockAccess().getInteractionsequenceAssignment_1(), "rule__GlobalInteractionBlock__InteractionsequenceAssignment_1");
					put(grammarAccess.getSpawnAccess().getRoleNameAssignment_0(), "rule__Spawn__RoleNameAssignment_0");
					put(grammarAccess.getSpawnAccess().getTargetProtocolNameAssignment_2(), "rule__Spawn__TargetProtocolNameAssignment_2");
					put(grammarAccess.getSpawnAccess().getParametersAssignment_3_2(), "rule__Spawn__ParametersAssignment_3_2");
					put(grammarAccess.getSpawnAccess().getParametersAssignment_3_3_2(), "rule__Spawn__ParametersAssignment_3_3_2");
					put(grammarAccess.getSpawnAccess().getCurrentRolesAssignment_5(), "rule__Spawn__CurrentRolesAssignment_5");
					put(grammarAccess.getSpawnAccess().getTargetRolesAssignment_7(), "rule__Spawn__TargetRolesAssignment_7");
					put(grammarAccess.getSpawnAccess().getCurrentRolesAssignment_8_1(), "rule__Spawn__CurrentRolesAssignment_8_1");
					put(grammarAccess.getSpawnAccess().getTargetRolesAssignment_8_3(), "rule__Spawn__TargetRolesAssignment_8_3");
					put(grammarAccess.getDoAccess().getTargetProtocolNameAssignment_1(), "rule__Do__TargetProtocolNameAssignment_1");
					put(grammarAccess.getDoAccess().getArgumentsAssignment_2_1(), "rule__Do__ArgumentsAssignment_2_1");
					put(grammarAccess.getDoAccess().getArgumentsAssignment_2_2_1(), "rule__Do__ArgumentsAssignment_2_2_1");
					put(grammarAccess.getDoAccess().getCurrentRolesAssignment_4(), "rule__Do__CurrentRolesAssignment_4");
					put(grammarAccess.getDoAccess().getTargetRolesAssignment_6(), "rule__Do__TargetRolesAssignment_6");
					put(grammarAccess.getDoAccess().getCurrentRolesAssignment_7_1(), "rule__Do__CurrentRolesAssignment_7_1");
					put(grammarAccess.getDoAccess().getTargetRolesAssignment_7_3(), "rule__Do__TargetRolesAssignment_7_3");
					put(grammarAccess.getInterruptibleAccess().getBodyAssignment_1(), "rule__Interruptible__BodyAssignment_1");
					put(grammarAccess.getInterruptibleAccess().getRoleNamesAssignment_3(), "rule__Interruptible__RoleNamesAssignment_3");
					put(grammarAccess.getInterruptibleAccess().getSignaturesAssignment_5(), "rule__Interruptible__SignaturesAssignment_5");
					put(grammarAccess.getInterruptibleAccess().getRoleNamesAssignment_6_2(), "rule__Interruptible__RoleNamesAssignment_6_2");
					put(grammarAccess.getInterruptibleAccess().getSignaturesAssignment_6_4(), "rule__Interruptible__SignaturesAssignment_6_4");
					put(grammarAccess.getContinueAccess().getLoopNameAssignment_1(), "rule__Continue__LoopNameAssignment_1");
					put(grammarAccess.getRecursionAccess().getLoopNameAssignment_1(), "rule__Recursion__LoopNameAssignment_1");
					put(grammarAccess.getRecursionAccess().getBodyAssignment_2(), "rule__Recursion__BodyAssignment_2");
					put(grammarAccess.getParallelAccess().getBranchesAssignment_1(), "rule__Parallel__BranchesAssignment_1");
					put(grammarAccess.getParallelAccess().getBranchesAssignment_2_1(), "rule__Parallel__BranchesAssignment_2_1");
					put(grammarAccess.getChoiceAccess().getRoleAssignment_2(), "rule__Choice__RoleAssignment_2");
					put(grammarAccess.getChoiceAccess().getBranchesAssignment_3(), "rule__Choice__BranchesAssignment_3");
					put(grammarAccess.getChoiceAccess().getBranchesAssignment_4_1(), "rule__Choice__BranchesAssignment_4_1");
					put(grammarAccess.getMessageAccess().getSignatureAssignment_0(), "rule__Message__SignatureAssignment_0");
					put(grammarAccess.getMessageAccess().getSenderAssignment_2(), "rule__Message__SenderAssignment_2");
					put(grammarAccess.getMessageAccess().getReceiverAssignment_4(), "rule__Message__ReceiverAssignment_4");
					put(grammarAccess.getMessageSignatureAccess().getOperatorAssignment_0(), "rule__MessageSignature__OperatorAssignment_0");
					put(grammarAccess.getMessageSignatureAccess().getPayloadTypesAssignment_2_0(), "rule__MessageSignature__PayloadTypesAssignment_2_0");
					put(grammarAccess.getMessageSignatureAccess().getPayloadTypesAssignment_2_1_1(), "rule__MessageSignature__PayloadTypesAssignment_2_1_1");
					put(grammarAccess.getPayloadTypeAccess().getPayloadAssignment_0(), "rule__PayloadType__PayloadAssignment_0");
					put(grammarAccess.getPayloadTypeAccess().getDataTypeAssignment_1(), "rule__PayloadType__DataTypeAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.scribble.ui.contentassist.antlr.internal.InternalScribbleParser typedParser = (org.scribble.ui.contentassist.antlr.internal.InternalScribbleParser) parser;
			typedParser.entryRuleScribbleProgram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ScribbleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScribbleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
