/*
* generated by Xtext
*/
package org.scribble.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.scribble.services.ScribbleGrammarAccess;

public class ScribbleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ScribbleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.scribble.parser.antlr.internal.InternalScribbleParser createParser(XtextTokenStream stream) {
		return new org.scribble.parser.antlr.internal.InternalScribbleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ScribbleProgram";
	}
	
	public ScribbleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ScribbleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
