/*
 * generated by Xtext
 */
package org.scribble;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScribbleRuntimeModule extends org.scribble.AbstractScribbleRuntimeModule {

}
