/*
* generated by Xtext
*/
package org.scribble.ui.contentassist;

import org.scribble.ui.contentassist.AbstractScribbleProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ScribbleProposalProvider extends AbstractScribbleProposalProvider {

}
