/*
 * generated by Xtext
 */
package org.scribble.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScribbleUiModule extends org.scribble.ui.AbstractScribbleUiModule {
	public ScribbleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
