/*
* generated by Xtext
*/
package org.scribble;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ScribbleUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.scribble.ui.internal.ScribbleActivator.getInstance().getInjector("org.scribble.Scribble");
	}
	
}
